### ISSUE TITLE
Unable to install in Julia 1.1

### ISSUE THREAD

**Issue by pazzo83** [JuliaWeb/WebSockets.jl#130]
Trying to add WebSockets with the julia package command line, I get the following exception:
```
(v1.1) pkg> add WebSockets
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HTTP [cd3eb016]:
 HTTP [cd3eb016] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.4.0-0.4.3, 0.5.0, 0.5.2-0.5.5, 0.5.7, 0.6.0-0.6.14, 0.7.0-0.7.1, 0.8.0] or uninstalled
 ├─restricted to versions 0.8.0 by an explicit requirement, leaving only versions 0.8.0
 └─restricted by compatibility requirements with WebSockets [104b5d7c] to versions: [0.6.14, 0.7.0-0.7.1] — no versions left
   └─WebSockets [104b5d7c] log:
     ├─possible versions are: [0.0.1-0.0.6, 0.1.0-0.1.2, 0.2.0-0.2.3, 0.3.0, 0.4.0, 0.5.0, 1.0.0-1.0.3, 1.1.0-1.1.1, 1.2.0] or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.6, 0.1.0-0.1.2, 0.2.0-0.2.3, 0.3.0, 0.4.0, 0.5.0, 1.0.0-1.0.3, 1.1.0-1.1.1, 1.2.0]
     └─restricted by julia compatibility requirements to versions: [1.0.0-1.0.3, 1.1.0-1.1.1, 1.2.0] or uninstalled, leaving only versions: [1.0.0-1.0.3, 1.1.0-1.1.1, 1.2.0]
```

**Comment by hustf** [comment]
Http is restricted to 0.8 by an " external requirement". I believe this is because you have added http directly. If you remove this, http will still work but indirectly. You can also keep it as a direct requirement, but not in the same project environment.

Http 0.8 is just a week or so old. We will release a compatible version soon. I believe your dependency tree will be more stable through future release cycles if you use lower level packages like http indirectly when possible. We try to keep the websocket api backwards compatible.

**Comment by mdpradeep** [comment]
@hustf, just wanted to check if a new version compatible with HTTP-0.8 will be available soon ?

**Comment by hustf** [comment]
Definitely. Some days after the logging pull request is merged. That is a large change, so I would like a competent review. I dont trust my own competence without at least also making an ad hoc mini benchmark to ensure no deteriorations sneaked in.

**Comment by hustf** [comment]
@mdpradeep, sorry for the premature promise above. As you may have seen, release 1.3.1 just added some strict tests while still referring HTTP 0.7, and also provides an ugly way to override HTTP settings for default number of simultaneous connections.

Looking more closely at what's actually contained in HTTP 0.8, I think it 
1) Gets past a historical limitation where Julia was bad at using keyword arguments. This led to defining lots of types, or layers of abstraction, which is not a friendly way to define an API. The new approach, I think, allows us to use the details we need for our applications without learning about everything else.

2) Uses multiple dispatch, Julia's main strength, behind the scenes. 

3) Fits better with serving other things than file trees. I've written some file handling servers myself, and could never fully guarantee they're safe.

My hunch now is that ServerWS, WebSockets.ServerOptions, and some internal  functions are going to disappear before reaching HTTP 0.8. We won't keep anything outside of treating with WebSockets here without some reason. If those API function are going away, a release with deprecation warnings and hopefully suggestions for user code restructuring should come first.

Current work in branch issue130 (far from useable).

**Comment by hustf** [comment]
Closing this, as a HTTP 0.8 release is now made. It will be reflected in METADATA soon.
