### ISSUE TITLE
Failed to open a websocket server path

### ISSUE THREAD

**Issue by woshidama323** [JuliaWeb/WebSockets.jl#154]
Env  ubuntu18.4
Julia 1.2

Question:
 When using websocket like this below 
I got an error
```
> WebSockets.open((-)->nothing,"ws://localhost:9050/ws")
> HTTP.Messages.Response:
> """
> HTTP/1.1 404 Not Found
> Content-Type: text/plain; charset=utf-8
> X-Content-Type-Options: nosniff
> Date: Thu, 28 Nov 2019 08:01:34 GMT
> Content-Length: 19
```

But the websocket server is ok and I can access this server by using command ws
ws "ws://localhost:9050/ws" 

So, what's the reason ?

**Comment by hustf** [comment]
How do you know you don't connect? This should open a client websocket,
immediately exit, and then close?

**Comment by hustf** [comment]
I would have to look up the 404 message. Perhaps you actually do connect. But since you immediately exit and close, which http response would you actually expect?

**Comment by woshidama323** [comment]
@hustf I need to keep the ws connection alive always and can read the message from the ws server continually. You mean client had already connected to the ws server ? I will test it again
