### ISSUE TITLE
hope release a new version

### ISSUE THREAD

**Issue by zsz00** [JuliaWeb/WebSockets.jl#178]
@hustf

**Comment by AbhimanyuAryan** [comment]
yes but I think there are some issues left https://github.com/JuliaWeb/WebSockets.jl/issues/180

**Comment by hustf** [comment]
WebSockets.jl now has a new version, requiring Julia 1.8.2+ and HTTP 1.1.0 to 1.5. Hopefully, this solves the issue; simply do `Pkg.update()`!
