### ISSUE TITLE
Release version 1.5.10

### ISSUE THREAD

**Issue by dantaras** [JuliaWeb/WebSockets.jl#179]
Hi @hustf,

Could you please release version 1.5.10 of `WebSockets`? The only change not released from master is the HTTP.jl compat entry and it's holding us back from upgrading to HTTP.jl 1.0

Thank you!

**Comment by hustf** [comment]
We don't release the current master because it is not actually compatible with HTTP  > v0.9.17.

The unreleased `master`, upon precompilation, complains:
```
Precompiling project...
  ✗ WebSockets
  3 dependencies successfully precompiled in 5 seconds. 13 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
     Testing Running tests...
WARNING: could not import HTTP.handle into WebSockets
WARNING: could not import HTTP.Transaction into WebSockets
```

Pull requests welcome!

**Comment by dantaras** [comment]
Oh, I thought it's just a formality to release latest master. Didn't realise it's not actually compatible. I'll close this then. Thanks for responding.
