### ISSUE TITLE
The version 0.3.3 is still buggy to binary data

### ISSUE THREAD

**Issue by altieresdelsent** [JuliaWeb/WebSockets.jl#18]
I don't know why, but in the julia version 0.3.3, when I do "Pkg.add("WebSockets") I still get the older version, without the fix to accept binary data. When I manually copy the current version over the older, it works.

**Comment by hustf** [comment]
This is a bit outdated. Currently, installing on Julia version 0.7 (nightly) does not work because httpcommon does not work. Closing this one for now.

Binary tests against a real client are still missing.
