### ISSUE TITLE
More tests needed.

### ISSUE THREAD

**Issue by sbromberger** [JuliaWeb/WebSockets.jl#21]
Currently at 3%.

**Comment by astrieanna** [comment]
A major thing here is just setting things up to make it easy to test making an actual connection. Or at least mocking out a WebSocket so that we can check that `ping()` or `close()` send the right thing.

Does anyone have any specific suggestions for implementing tests of the sending and/or the reading functions? Mocking out a WebSocket seems like a reasonable option, which would mean making that an abstract type with two implementations -- the "real" one and the test/mock one.

**Comment by hustf** [comment]
The ping - pong is not yet added to the tests, but the framework is in place at least. Speed tests would also be interesting here. Now at 78% coverage.

**Comment by hustf** [comment]
PR #80 adds a ping-pong tests, but the results are not logged. Internet Explorer 11 pings quite often by itself, as can be observed by adding a println to Websocket pong.

**Comment by EricForgy** [comment]
Hi guys,

I am considering a revamp of the test suite. It would be great if we can make a wish list of tests.

The README states:

> ## What can you do with a `WebSocket`?
> You can:
>
> * `write` data to it
> * `read` data from it
> * send `ping` or `pong` messages
> * `close` the connection

With such little promised, I'm tempted to run some very simple tests:

```julia
opcodes = ["text", "binary", "close", "ping", "pong"]

clients = ["Julia", "Chrome", "Firefox", "IE", "Node", "PhantomJS"]
for c in clients
    for o in opcodes
        # Julia server writes $(o) to $(c) client
        # Julia server reads $(o) from $(c) client
    end
end

servers = ["Julia", "Node", "echo.websocket.org"]
for s in servers
    for o in opcodes
        # Julia client writes $(o) to $(s) server
        # Julia client reads $(o) from $(c) server
    end
end
```

I think all of the above can be written in ~100 lines of code. I am really hoping to get the `change_dependencies` merged and the current test suite is not easy for me to work with.

**Comment by hustf** [comment]
Confirmed. It's really hard to work with.
I'm having a go at change_dependencies and will try to assist with the tests in the process.
You've come a long way already, congratulations!

**Comment by hustf** [comment]
Now at 96 % coverage, without browser tests. They are a bit unreliable on ci.
