### ISSUE TITLE
Convert in-file comments to 0.4 docs

### ISSUE THREAD

**Issue by astrieanna** [JuliaWeb/WebSockets.jl#26]
Instead of comments, we should convert to the new documentation stuff. This could be an opportunity to add usage examples to the documentation for each function.

```
VERSION < v"0.4-" && using Docile

@doc doc"Documentation goes here."
function ping(ws::WebSocket)
end
```

**Comment by hustf** [comment]
This was actually implemented in the previous release. Closing.
