### ISSUE TITLE
Better Logging

### ISSUE THREAD

**Issue by astrieanna** [JuliaWeb/WebSockets.jl#28]
A major thing that WebSockets.jl currently lack is a good way to log errors and generally communicate when things go wrong to the user-application. This currently makes debugging changes frustrating (have to add println logging all over), but will also make debugging client applications potentially frustrating.
## Logging Options

Since we're using HttpServer anyway, one option is to use its event system, which lets you trigger events and set functions to handle different "types" of events.

Actual logging package options include:
- Logging.jl https://github.com/kmsquire/Logging.jl
- Lumberjack.jl https://github.com/forio/Lumberjack.jl

I think `Logging.jl` looks like the best option... mostly because I got to the bottom of the README and felt like I was ready to start using it. It does basically what I was looking for -- various levels of logging, some potential for making it easy to filter WebSocket level logs separately from application level logs.

Does anyone else have opinions of how we should do logging better?

**Comment by hustf** [comment]
Websockets can be pretty fast and used as a supplement to javascript for interactivity. Whatever we do, an opt out with very small drawbacks should exist.

Logging on events work fine and does not affect this package. But it is pretty unsatisfactory without adding more events. Is that what you suggest?

Opening and closing files for logging is very slow. To be decently effective, a file logger would need to keep an open file for the duration of each websocket, or limit the logging to opening and closing of sockets.

The open file stream could be referenced in a global const array, and it could be the last websocket to leave's responsibility to close the file. For debugging, the files would be incomplete until you make a clean exit from all websockets. If you flush the stream after each write operation, this would slow the logger down.

It is hard to make a fast logger. Another option might be to include Websockets_debug.jl which users could rename for debugging or increased understanding.

**Comment by hustf** [comment]
Closed by release v0.3.1 (log tools in tests).
