### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by astrieanna** [JuliaWeb/WebSockets.jl#29]
A major thing that WebSockets.jl currently lacks is a good way to generally communicate when things go wrong to the user-application.

Sometimes, we should fail the handshake (by sending 400 Bad Request), but the functions aren't set up to pass the knowledge of the failure back up.

Part of this is also communicating when a connection is being closed. We may need to close the WebSocket at any time (due to, for example, the other end sending an invalid frame). We would like to let the application find out why the WebSocket closed, if it wants to. The other question is what to do if the socket closes when we're in the middle of reading/writing a data message for the user. Should we stop in the middle? For reading, this is obviously yes, and the question becomes what to do with the partial message -- do we give it to the application or just drop it?

**Comment by astrieanna** [comment]
Also, if we receive a close, we should let the application programmatically ask why (ask for the status code) and ask whether we or the other side sent the "first" close. Each side could simultaneously send closes with different status codes.

It's also possible that we should include a dictionary from close status codes to definitions (for the ones defined in the RFC which is about a dozen or so).

**Comment by hustf** [comment]
A reason for closing is transmitted as code. In the test script browsertest.html, a dictionary is added. Explanatory text is optional.
