### ISSUE TITLE
Non-blocking Read

### ISSUE THREAD

**Issue by ninjin** [JuliaWeb/WebSockets.jl#30]
Apologies if this is already supported and I have to admit that my network programming is a bit rusty, but as far as I can tell there is no way to perform a non-blocking read in WebSockets.jl.

**Comment by astrieanna** [comment]
You are correct. There is only a blocking read function.

To make sure I understand: you want a non-blocking version that's just like the existing (blocking) read, but immediately returns if there's nothing there?

This could involve some internal changes -- for example, blocking read waits for an entire message to be received, but non-blocking read would need to save the message-so-far if there isn't a whole message available yet.

**Comment by ninjin** [comment]
> To make sure I understand: you want a non-blocking version that's just like the existing (blocking) read, but immediately returns if there's nothing there?

Yes, that is exactly it.  I am trying to find a reference to an existing web socket library that does this for another language to check if it is really a good idea.

**Comment by astrieanna** [comment]
I mean, that seems like a fine implementation choice. I expect that
implementing it will require:

1. Decide how to differentiate read-blocking vs read-nonblocking.
(different names, read with different arguments, etc?)
2. Decide how to deal with partial messages. (how to save them, how to
resume, etc)
3. Pick a function from Base to check if there's stuff there to read
(without blocking).

The biggest thing is probably partial messages. Complete frames aren't too
bad (you just need to collect the payloads), but what if you only have
"part" of a frame, but the socket doesn't have anything left to read? This
seems like an unlikely edgecase, but one worth deciding how to deal with. I
assume you don't want to block on seeing the rest of the frame, so there
should be somewhere to stick the stuff you've read so far.

Making it possible to interleave non-blocking and blocking calls to read
would require making both versions deal with partially read frames/messages.

**Comment by StefanKarpinski** [comment]
In general, the Julian way is to have blocking APIs that yield to the scheduler and get concurrency by having many tasks. Which is what this already does, no? What's the motivating use case here?

**Comment by ninjin** [comment]
I think @StefanKarpinski was on the right track.  The use case was a server with multiple clients and once I brushed up on my rather rusty network programming it became apparent that a simple `@async begin ... end` server task which reads from a message queue that is fed by each of the client connection tasks, really was what I wanted all along.  Sorry about the noise, closing.

**Comment by StefanKarpinski** [comment]
Cool.
