### ISSUE TITLE
Tag a new version + fix old version tags

### ISSUE THREAD

**Issue by WestleyArgentum** [JuliaWeb/WebSockets.jl#40]
I see one version, `0.0.4` tagged in the github repo, and up to version `0.0.6` tagged in metadata, but all of those are 2 years old at this point.

Is this stable enough that we can call it `1.0.0`? Or maybe we should at least tag `0.1.0`?

**Comment by shashi** [comment]
+1 for speedy resolution of this issue. 0.1.0 sounds fine for now.

**Comment by WestleyArgentum** [comment]
Cool, done

**Comment by shashi** [comment]
:+1:
