### ISSUE TITLE
Echo server receiving/sending UInt8's

### ISSUE THREAD

**Issue by jkleiser** [JuliaWeb/WebSockets.jl#48]
Using Julia-0.4.0.app on my Mac, I try this Echo server:

```
using HttpServer
using WebSockets

wsh = WebSocketHandler() do req, client
  while true
    msg = read(client)
    write(client, msg)
    println("Did receive & send: $msg")
  end
end

server = Server(wsh)
run(server, 8080)
```

When I send "aaa", I get this in the console:
`Did receive & send: UInt8[0x61,0x61,0x61]`
... and in my client I get nothing back.

I would also like to get rid of this:

```
WARNING: Base.TcpSocket is deprecated, use Base.TCPSocket instead.
  likely near /Users/jkleiser/.julia/v0.4/WebSockets/src/WebSockets.jl:36
```

**Comment by shashi** [comment]
This is how the API has been all along (I'm not sure if this is not correct)

You need to use `bytestring(read(client))` on the data to convert it into a string.

**Comment by jkleiser** [comment]
Thanks. Works fine with `bytestring(read(client))`.
To get rid of the `WARNING: Base.TcpSocket is deprecated`, I tried to change line 34 of WebSockets.jl into `const TCPSock = Base.TCPSocket`, but I still get the warning. What have I missed?

**Comment by hustf** [comment]
Outdated reply; see take! and String documentation.
