### ISSUE TITLE
How to detect client disconnected?

### ISSUE THREAD

**Issue by jkleiser** [JuliaWeb/WebSockets.jl#49]
Is it possible?

**Comment by ryanmjacobs** [comment]
You should be able to access the `isopen()` method defined in [WebSockets.jl#L199](https://github.com/JuliaWeb/WebSockets.jl/blob/master/src/WebSockets.jl#L199).
```Julia
# A WebSocket is closed if the underlying TCP socket closes, or if we send or
# receive a close message.
Base.isopen(ws::WebSocket) = !ws.is_closed && isopen(ws.socket)
```

So given a client, you can check whether or not they are still online:
```Julia
if WebSockets.isopen(client) == false
    println("client is offline")
end
```

**Comment by hustf** [comment]
Outdated reply due to pr #69.
