### ISSUE TITLE
WebSocket Client

### ISSUE THREAD

**Issue by bryaan** [JuliaWeb/WebSockets.jl#52]
We have a server so how about a client?

Would this be easy to implement?

**Comment by tmlbl** [comment]
I am interested in working on this, can anyone point me in the right direction?

**Comment by BryanARivera** [comment]
Figuring out how meteor checks for updated code would be a good place to
start.  It might be a simple one liner, or it could be systemic.

**Comment by hustf** [comment]
Clients are called in the current tests. They pick from common browsers and phantoms, whichever are available on the system running the test. The code for opening linux browsers may or may not be working for the browsers -  I don't have linux. Try Pkg.test("WebSockets") if you have linux.

**Comment by hgeorgako** [comment]
Having an example of how to use a websocket client from julia would be very useful in the documentation. Can't find anything online. All examples reference non julia clients.

**Comment by hustf** [comment]
This package implements server side only. Dandelionwebsockets aims to implement both, but there is a current lack of maintainers.

The current examples are written with anonymous functions, which I personally find complicates debugging. The examples in the test folders are written in a quite different style which you may possibly find easier to follow, depending on where you are coming from. The client side interfaces are written in the most basic javascript. I find chrome the most user friendly client side implementation.

I hope I understood  your issue reasonably well, and would appreciate if you could share details of your use case.

**Comment by hustf** [comment]
You may also want to study Blink, Atom, Electron, IJuliaEscher and other dependendants. I do not find those as easy to understand, but then that may be different for you.

**Comment by hgeorgako** [comment]
Use case is fairly simple. I need to connect to a websocket that disseminates timeseries data in the form of a json object. 
An event looks like: 

{“Time”:”2017-12-12 04:34:23.324343”, “Val”:123}

I want to take every event that arrives and (in Julia) store it in an array. After 100 events have arrived, I want to sum the entries and flush the array.

**Comment by hustf** [comment]
I am travelling without a computer. One way you can get going is modifying directly the test files; 
Put your code in handler_functions_websockets_general_test line.jl  line 16. Strip away what you dont need later. 

What I call the client side code resides in browsertest.html

Now output from your code is the tricky part. Write to a file or write to a mutable const are two options. Calling outside functions with the output from websocket communication is another. In time, I plan to give an example communicating with other processes over a Zmq queue.
