### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dioptre** [JuliaWeb/WebSockets.jl#53]

**Comment by aviks** [comment]
No.

**Comment by dioptre** [comment]
Ok, do you need help? I'd like to get SSL working and would love to find a way I can help. Happy to take it offline if anyone in this group can spare 15 minutes.

**Comment by quinnj** [comment]
Pull Requests are always welcome! I recently started using this package as well, so I'd be happy to help review/test changes you submit. If I remember correctly, there was a good TODO of items in the source code too, if you're looking for other things to work on.

**Comment by tmlbl** [comment]
@dioptre I am also interested in getting SSL working. Sent you an email.

**Comment by ceremcem** [comment]
I'm just curious, what is the point of getting an SSL support while there is good stable reverse proxies which do this job for you?

**Comment by dioptre** [comment]
Yes I thought about that hack, and it's a fallback I'll reluctantly use if
getting TLS working proves to be difficult.... Thanks for the suggestion!

TLS is supported by HttpServer, so it shouldn't take much work to get it
going though! When I have time I'll get back to it.

**Comment by MikeInnes** [comment]
Please feel free to open new issues for any of these points.
