### ISSUE TITLE
using with ProtoBuf.jl

### ISSUE THREAD

**Issue by zahachtah** [JuliaWeb/WebSockets.jl#58]
I want to send and receive data using protobuf.jl. The readproto(IO,type) and writeproto(IO,type) writes to a IO stream. I thought I could use the websocket for this but can't get it to work, neither with:

writeproto(client.socket.buffer,mytype()) or
writeproto(client.socket,mytype())

The only way I get it to work now is this uglyhack:

```julia
ion = PipeBuffer()
while true
    msg = read(client)
    write(iob,msg)
    test = readproto(iob,mytype())
    print(test)
    writeproto(iob,mytype())
    write(client,read(iob))
end
```

what I am trying to get working is:

```julia
while true
    test = readproto(client,mytype())
    print(test)
    writeproto(client,mytype())
end
```

Also, is anyone working on wss protocol?

Many thanks for any info and help

**Comment by shashi** [comment]
If `writeproto` eventually calls `write(::IO, ::Array{UInt8})`, this should work.

What error do you get with the version you are trying to make work?

**Comment by zahachtah** [comment]
when changing this:

´´´julia
ion = PipeBuffer()
while true
    msg = read(client)
    write(iob,msg)
    test = readproto(iob,mytype())
    print(test)
    writeproto(iob,mytype())
    write(client,read(iob))
end
´´´

to 

´´´
ion = PipeBuffer()
while true
    msg = read(client)
    write(iob,msg)
    test = readproto(iob,mytype())
    print(test)
    writeproto(client.socket.buffer,com(id=[1,2],val=XY))
end
´´´

I get:

´´´
ERROR (unhandled task failure): WebSocket reader cannot handle incoming messages without mask. See http://tools.ietf.org/html/rfc6455#section-5.3
 in read_frame at /Users/Raukhur/.julia/v0.4/WebSockets/src/WebSockets.jl:274
 in read at /Users/Raukhur/.julia/v0.4/WebSockets/src/WebSockets.jl:310
 [inlined code] from /Users/Raukhur/Google Drive/Game/server.jl:13
 in anonymous at task.jl:447
´´´

**Comment by zahachtah** [comment]
Interestingly I didn't change the read related lines....

**Comment by zahachtah** [comment]
```julia
println(typeof(client.socket.buffer))
```
gives
```julia
Base.AbstractIOBuffer{Array{UInt8,1}}
```

**Comment by tanmaykm** [comment]
ProtoBuf messages do not have any end-of-message marker. Reading and writing directly will work only in a strict request-response scenario with only one message is sent at any time, but may fail otherwise.

Usually this is handled by preceding messages with a header that mentions the size. Please see: https://developers.google.com/protocol-buffers/docs/techniques

**Comment by zahachtah** [comment]
Thanks @tanmaykm for the link. so according to it it suggests:

> The easiest way to solve this problem is to write the size of each message before you write the message itself. When you read the messages back in, you read the size, then read the bytes into a separate buffer, then parse from that buffer

which I guess I have solved unintentionally by using a PipeBuffer as in the working example above.

Would it be a good idea to build protobuf use into websockets in a better way?

Anyhow, I will use the working code for now. Thanks all who gave your insights.

**Comment by tanmaykm** [comment]
@zahachtah Simply using a `PipeBuffer` still may not work in cases where multiple messages are written before the reader gets to read. E.g.:
````julia
julia> using ProtoBuf

julia> type MyMsg
           msg::String
       end

julia> pb = PipeBuffer();

julia> writeproto(pb, MyMsg("Hello"));

julia> writeproto(pb, MyMsg(" "));

julia> writeproto(pb, MyMsg("World"));

julia> readproto(pb, MyMsg("")) # first two msgs lost
MyMsg("World")
```` 

The wright way is to have a length header for each message.
E.g. this would work:
````julia
julia> using ProtoBuf

julia> type MyMsg
           msg::String
       end

julia> pb = PipeBuffer();

julia> function write_msg(io, msg)
           iob = IOBuffer()
           writeproto(iob, msg)
           buff = takebuf_array(iob)
           ProtoBuf.write_varint(io, length(buff))
           write(io, buff)
           nothing
       end

julia> function read_msg(io, msg)
           len = ProtoBuf.read_varint(io, Int)
           buff = Array(UInt8, len)
           read!(io, buff)
           readproto(IOBuffer(buff), msg)
       end

julia> write_msg(pb, MyMsg("Hello"));

julia> write_msg(pb, MyMsg(" "));

julia> write_msg(pb, MyMsg("World"));

julia> read_msg(pb, MyMsg(""))
MyMsg("Hello")

julia> read_msg(pb, MyMsg(""))
MyMsg(" ")

julia> read_msg(pb, MyMsg(""))
MyMsg("World")
````

I am not sure if a generic implementation would be useful. Because there may be different languages/implementations at both ends of a websocket.

**Comment by zahachtah** [comment]
@tanmaykm this is great, thanks for showing me how its done. This may be usefull to add to the protobuff.jl readme file?

**Comment by tanmaykm** [comment]
@zahachtah Yes, that will be useful.
I may be able to add it in a few days time. Please feel free to send a PR to `ProtoBuf.jl` in the meantime.
You may also close this issue if `WebSockets.jl` is working fine with these changes.
