### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by darim1** [JuliaWeb/WebSockets.jl#59]
Hi,

I am trying to get this working, but figured out that the example might create memory leaks. I think the problem refers to Julia, since the while loop would not allow the garbage collector to invoke properly. 
In consequence Julia memory usage will increase continously. 

This could be avoided by adding a gc() inside the loop, but this also impacts performance. 

``` jl
using HttpServer
using WebSockets

wsh = WebSocketHandler() do req,client
    while true
        gc() # Explicit invocation of Julia's garbage collector
        msg = read(client)
        write(client, msg)
    end
  end

server = Server(wsh)
run(server,8080)
```

Are there other possibilities to code this in Julia, e.g. by using a callback?

Thanks,
Daniel

**Comment by shashi** [comment]
I don't think this is true, `read` and `write` are both blocking during which the gc can come in and clean up.
