### ISSUE TITLE
Follow-up to pull request #62

### ISSUE THREAD

**Issue by hustf** [JuliaWeb/WebSockets.jl#63]
That pull request got merged before I had a chance to improve it.  I took the many forks as an indication that people use this package with their own fixes. 

Quote tkelman:

> what are you using that was first in 0.16? looks like 0.9.5 might be good enough for take!

A low Compat number may enable some combinations of packages and Julia. I can follow up with another PR to keep the version number as low as possible fora follow-up.  

What about the badges? They say 0.6.1 fail. Why is that? And could we do something to indicate that this also works on Windows? I guess I need to get up to date on how the evaluation system works.

**Comment by hustf** [comment]
It turns out dropping 0.4 is not necessary. It may even still work in 0.3 - to be tested before submit.
I have converted comments to inline docs, and cleaned indents.

**Comment by hustf** [comment]
0.3 won't work of course, due to pre-compilation. #64 drops dead code for Julia 0.3.

**Comment by shashi** [comment]
Thanks for doing this. I will close this since your changes are now released. Cheers!
