### ISSUE TITLE
The dependency on jquery could be removed in examples/chat-client.html

### ISSUE THREAD

**Issue by widged** [JuliaWeb/WebSockets.jl#85]
As I played with the examples, I made changes to the js code in examples/chat-client.html. https://github.com/widged/WebSockets.jl/blob/master/examples/chat-client.html. 
Let me know if this is of any interest to you and whether you are ok with es6 or prefer strict es5.

**Comment by hustf** [comment]
Pull request welcome!
IE11 people, if this does not work, can use the old versions. 
And it is good to get rid of the dependency.

**Comment by widged** [comment]
Done. Do not hesitate to let me know if you need more information.

**Comment by hustf** [comment]
Before this pull request, Firefox indicated:
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead
[Learn More]
jquery-1.9.1.min.js:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
jquery.js:68

**Comment by hustf** [comment]
Part of tagged release 0.5.
