### ISSUE TITLE
How to get the IP address of the request?

### ISSUE THREAD

**Issue by essenciary** [JuliaWeb/WebSockets.jl#95]
Is it possible to get the IP address of the request, please? 

With `HttpServer` it could be done like this: 
```julia 
http.events["connect"] = (http_client) -> handle_connect(http_client)

function handle_connect(client::HTTP.Client)
  try
    ip, port = getsockname(isa(client.sock, MbedTLS.SSLContext) ? client.sock.bio : client.sock)
  catch
  end
 end
```

**Comment by hustf** [comment]
I would continue to use HttpServer for that so far. There are comments about supporting events in the future with HTTP, in the source code. There is also a mention of using something else than libuv for establishing the connections in the future, somewhere.

**Comment by essenciary** [comment]
Oops, I had too many tabs open - this issue was meant for `HTTP.jl`
